const cardsImages : any = {
    "2C" : '/Images/Cards/2C.png',
    "3C" : '/Images/Cards/3C.png',
    "4C" : '/Images/Cards/4C.png',
    "5C" : '/Images/Cards/5C.png',
    "6C" : '/Images/Cards/6C.png',
    "7C" : '/Images/Cards/7C.png',
    "8C" : '/Images/Cards/8C.png',
    "9C" : '/Images/Cards/9C.png',
    "10C" : '/Images/Cards/10C.png',
    "11C" : '/Images/Cards/11C.png',
    "12C" : '/Images/Cards/12C.png',
    "13C" : '/Images/Cards/13C.png',
    "14C" : '/Images/Cards/14C.png',
    "2D" : '/Images/Cards/2D.png',
    "3D" : '/Images/Cards/3D.png',
    "4D" : '/Images/Cards/4D.png',
    "5D" : '/Images/Cards/5D.png',
    "6D" : '/Images/Cards/6D.png',
    "7D" : '/Images/Cards/7D.png',
    "8D" : '/Images/Cards/8D.png',
    "9D" : '/Images/Cards/9D.png',
    "10D" : '/Images/Cards/10D.png',
    "11D" : '/Images/Cards/11D.png',
    "12D" : '/Images/Cards/12D.png',
    "13D" : '/Images/Cards/13D.png',
    "14D" : '/Images/Cards/14D.png',
    "2S" : '/Images/Cards/2S.png',
    "3S" : '/Images/Cards/3S.png',
    "4S" : '/Images/Cards/4S.png',
    "5S" : '/Images/Cards/5S.png',
    "6S" : '/Images/Cards/6S.png',
    "7S" : '/Images/Cards/7S.png',
    "8S" : '/Images/Cards/8S.png',
    "9S" : '/Images/Cards/9S.png',
    "10S" : '/Images/Cards/10S.png',
    "11S" : '/Images/Cards/11S.png',
    "12S" : '/Images/Cards/12S.png',
    "13S" : '/Images/Cards/13S.png',
    "14S" : '/Images/Cards/14S.png',
    "2H" : '/Images/Cards/2H.png',
    "3H" : '/Images/Cards/3H.png',
    "4H" : '/Images/Cards/4H.png',
    "5H" : '/Images/Cards/5H.png',
    "6H" : '/Images/Cards/6H.png',
    "7H" : '/Images/Cards/7H.png',
    "8H" : '/Images/Cards/8H.png',
    "9H" : '/Images/Cards/9H.png',
    "10H" : '/Images/Cards/10H.png',
    "11H" : '/Images/Cards/11H.png',
    "12H" : '/Images/Cards/12H.png',
    "13H" : '/Images/Cards/13H.png',
    "14H" : '/Images/Cards/14H.png',
}

export const getCard = (value : string, color : string) => {
    let cardString = value + color;
    return cardsImages[cardString]
}